### ISSUE TITLE
'No such module' when trying to import framework in playground

### ISSUE THREAD

**Issue by andriichernenko** [asmallteapot/cocoapods-playgrounds#12]
I am trying to create playground with Alamofire. I am doing everything according to the instructions (including building the scheme), but the framework can't seem to be imported in the playground:
![screen shot 2016-02-19 at 18 27 48](https://cloud.githubusercontent.com/assets/4421971/13183329/aaca8682-d736-11e5-915d-b823da55dbc0.png)

My Xcode version is 7.2.1 (7C1002), CocoaPods version is 1.0.0.beta.3 (tried 0.39.0 as well).

Am I missing something?

**Comment by altyus** [comment]
I'm seeing the same behavior.

**Comment by neonichu** [comment]
I'm assuming you don't see any build errors. Can you try deleting DerivedData and building the scheme again?

**Comment by andriichernenko** [comment]
@neonichu no, there were no build errors. And yes, removing DerivedData and building the scheme helped, thanks!

**Comment by kiwikanji** [comment]
I am getting this same error even after deleting derived data and rebuilding.

Any more suggestions?
