### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by JaviSoto** [asmallteapot/cocoapods-playgrounds#13]
I see that the `playground` CLI tool supports specifying the `--platform`, but not when using `pod playgrounds`. Can you add this? :)

**Comment by neonichu** [comment]
Definitely, there's even a TODO for it already ;) https://github.com/neonichu/ThisCouldBeUsButYouPlaying/blob/master/lib/cocoapods-playgrounds/command/playgrounds.rb#L24

**Comment by neonichu** [comment]
Shipped as https://github.com/neonichu/ThisCouldBeUsButYouPlaying/releases/tag/v1.2.0
