### ISSUE TITLE
Module not found when defining `module_name`

### ISSUE THREAD

**Issue by keith** [asmallteapot/cocoapods-playgrounds#14]
For [Mapper](https://github.com/lyft/mapper) I have defined `module_name` to be `Mapper` since I had to push it to CocoaPods as `ModelMapper`. It seems like when defining this key, importing either `ModelMapper` or `Mapper` in the generated playground ends up with a `No such module` error.

**Comment by neonichu** [comment]
Hm, `import Mapper` works just fine for me for that Pod. Good point, though, that this should take the `module_name` attribute into account when generating code. Did you try deleting DerivedData? :)

**Comment by keith** [comment]
I did ddd, let me try it again and see what went wrong.

**Comment by keith** [comment]
`¯\_(ツ)_/¯`
