### ISSUE TITLE
Not working with CocoaPods 1.0.0 beta

### ISSUE THREAD

**Issue by mgrebenets** [asmallteapot/cocoapods-playgrounds#16]
I'm trying to use this gem with CocoaPods version `1.0.0.beta6` and it doesn't work.
The `pod` command just doesn't find `playgrounds` sub-command.

At the same time it works with `0.39.0`.

Is it possible to use playgrounds with pre-release CocoaPods?

**Comment by neonichu** [comment]
It has been working in my testing. How do you switch between CP versions? Is it possible that you also switch `GEM_HOME` so that when you are using 1.0, the cocoapods-playgrounds gem isn't actually available?

**Comment by mgrebenets** [comment]
You are right. I was using RVM and got both pre-relase CP and playgrounds installed via `gem install` directly. Then I tried to have a `Gemfile` like this:

``` ruby
source "http://rubygems.org"
gem "cocoapods", "1.0.0.beta6"
gem "cocoapods-playgrounds"
```

and `bundle exec pod playgrounds` works as expected.
