### ISSUE TITLE
No support for private pods

### ISSUE THREAD

**Issue by mgrebenets** [asmallteapot/cocoapods-playgrounds#17]
This `playgrounds` sub-command is lacking support for private pods. If my pod depends on another private pod, the `pod install --no-repo-update` will fail to fetch private pods.

I have to specify _all_ of the privates pods directly then:

``` shell
pod playgrounds MyPod.podspec,/path/to/dependency-a.podspec,/path/to/dependency-b.podspec
```

It would be great to have support for `--sources` option for `playgrounds` too.

**Comment by neonichu** [comment]
I agree, but I'm wondering about a more holistic approach for passing in additional CLI arguments to the underlying call to `pod` — I'd rather not duplicate lots of logic here.

**Comment by mgrebenets** [comment]
Well, the "way out" could be to generate playground with no pods, then go into `Podfile` and add those manually and just run `bundle exec pod install`. The problem is that I can't get the playground generated, because it fails to resolve private dependencies.

It's a bit tedious to specify them all by hand, but totally doable though...

**Comment by neonichu** [comment]
Maybe an approach would be to have some kind of "generate only" option, so that one can manually run `pod install`, but all the files would be generated.

**Comment by neonichu** [comment]
Allright, the `--no-install` option is implemented now. Use this to just generate all the necessary files, then you can your custom spec repo to the generated Podfile and run `pod install` to get a usable Playground.
