### ISSUE TITLE
Preserve code in playground on update

### ISSUE THREAD

**Issue by mgrebenets** [asmallteapot/cocoapods-playgrounds#18]
This is rather a feature request.
Whenever I have big changes to the pod, such as new files or new dependency added, I need to update the playground.
However, at this time `pod playgrounds` runs in "generate" mode and wipes all my code in old playground.

It would be helpful to have an "update" option to preserve playground code and pages, or make "update" a default operation mode.

**Comment by neonichu** [comment]
I would advise to just use `pod update` directly instead as there's nothing else required for such an update.

**Comment by mgrebenets** [comment]
Hm... true, didn't think of that. Thanks.
