### ISSUE TITLE
unable to run the command `gem install cocoapods-playgrounds`

### ISSUE THREAD

**Issue by aziz-boudi4** [asmallteapot/cocoapods-playgrounds#19]
- I keep having an error when I want to run the command `gem install cocoapods-playgrounds.
  Here is the error that I get : 
  `ERROR:  While executing gem ... (Gem::FilePermissionError)
  You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.`
-  I also tried to run `sudo gem install cocoapods-playgrounds` and here is the error that I get:
  `ERROR:  While executing gem ... (Errno::EPERM)
  Operation not permitted - /usr/bin/carthage-play`

**Comment by minmadic** [comment]
I was having the same issue and was able to get the gem installed in a local/bin using this command:

sudo gem install cocoapods-playgrounds -n/usr/local/bin

I found this work around in this StackOverflow question:

http://stackoverflow.com/questions/31972968/cant-install-gems-on-os-x-el-capitan

**Comment by neonichu** [comment]
Yep, this is entirely an OS X 10.11 issue, sorry.
