### ISSUE TITLE
Allow for multiple pods

### ISSUE THREAD

**Issue by icanzilb** [asmallteapot/cocoapods-playgrounds#2]
Sometimes you need more than one pod when you want to try something in a playground. E.g. you very often need both RxSwift and RxCocoa (and sometimes the data sources pod).

I think it'd be great if you allow for a comma separated list when specifying the pods, eg something like this:

1) if pod name command line parameter contains ","
2) split name parameter by ","
3) add a "pod podname" line for each of the pods specified

Ta -daaa 🎉

**Comment by Vkt0r** [comment]
Yeah it could be very interesting having support for multiples pods in the same Playground 👍
