### ISSUE TITLE
Cannot reference framework from files under Sources

### ISSUE THREAD

**Issue by yfujiki** [asmallteapot/cocoapods-playgrounds#21]
This works beautiful for referencing framework from Playground file! Following example just imports 'Realm' framework that I incorporated using this CocoPod plugin.
<img width="442" alt="screen shot 2016-05-08 at 12 43 41 pm" src="https://cloud.githubusercontent.com/assets/879725/15099433/9f219bd2-151a-11e6-9a7f-be0f34528b56.png">

However, if I do the same from files under Sources, it cannot reference the same framework.
<img width="556" alt="screen shot 2016-05-08 at 12 43 25 pm" src="https://cloud.githubusercontent.com/assets/879725/15099462/37468792-151b-11e6-8b5b-da7abc627af0.png">

Is it a known issue? If it is, is there a workaround?

**Comment by meiguiai** [comment]
The same issue to me. From the apple document, the one condition is an active schema build for the import Framework(limited to one custom framework!!!). So manage schema, active RealmSwift schema
should be work.

**Comment by meiguiai** [comment]
Also You can see this line[https://github.com/CocoaPods/swift/issues/3/](url)

The author throw out one method, using symbol link to target framework. I tried it, but failed.
The true question is how to find the position of imported Frameworks.

**Comment by neonichu** [comment]
TBH, this feels like a Playgrounds bug to me, I think the frameworks search path is simply not including `CONFIGURATION_BUILD_DIR` of the workspace for compilation of files inside `Sources`. I'll open a radar for it, you might want to do the same.

**Comment by neonichu** [comment]
http://www.openradar.me/26482686
