### ISSUE TITLE
Support for CocoaPods subspecs

### ISSUE THREAD

**Issue by xcadaverx** [asmallteapot/cocoapods-playgrounds#23]
I'm trying to 'pod playgrounds RxSwift,RxCocoa,ChameleonFramework/Swift' and getting an "unable to find specification for 'Swift'" error. It has no problem grabbing the objective-C cocoapod at 'ChameleonFramework', but trying to grab the subspec fails.

**Comment by neonichu** [comment]
Seems like it is getting interpreted as a path, because of the local development Pod feature:

```
$ pod playgrounds ../../../Sources/Alamofire/Alamofire.podspec
```

I guess the logic for that could be smarter, e.g. by only treating arguments as a path if they end in `.podspec`.
