### ISSUE TITLE
Framework imports don't work in source swift file

### ISSUE THREAD

**Issue by tarun-talentica** [asmallteapot/cocoapods-playgrounds#26]
This is not a issue but an unsupported feature.

"pod playgrounds Alamofire" command created a workspace.
"import Alamofire" can be used in main playground file or playground pages. But if I add any swift file in source folder, I can't use any import statements for installed pods.

I am not sure if this is even supported by Apple.

**Comment by neonichu** [comment]
See #21 — AFAIK, this is simply not supported by Playgrounds right now.
