### ISSUE TITLE
Add support for newer libraries in Xcode 8

### ISSUE THREAD

**Issue by ajaysolleti** [asmallteapot/cocoapods-playgrounds#31]
```
import XCPlaygroundPage
XCPlaygroundPage.currentPage.needsIndefiniteExecution = true
```

is replaced by

```
import PlaygroundSupport
PlaygroundPage.current.needsIndefiniteExecution = true
```

> This change was mentioned in [Session 213 at WWDC 2016](https://developer.apple.com/videos/play/wwdc2016/213/).

[Reference](http://stackoverflow.com/a/37864618/159602)

**Comment by asmallteapot** [comment]
This was fixed in #49.
