### ISSUE TITLE
Use with Cocoapods 0.39.0

### ISSUE THREAD

**Issue by JoeFerrucci** [asmallteapot/cocoapods-playgrounds#32]
`gem install cocoapods-playgrounds` seems to install Cocoapods `1.0.1` (latest).

I need to stay on Cocoapods 0.39.0.

Is there quick fix for this, like specifying the version?

**Comment by neonichu** [comment]
Installing an older version of this gem might work, but I'm not sure if there was a release that supported 0.39 at all. You'd have to check the Git history.
