### ISSUE TITLE
Importing Framework in the Sources directory doesn't work

### ISSUE THREAD

**Issue by piercifani** [asmallteapot/cocoapods-playgrounds#33]
As the title says, if you try to import one of `Podspec`s that you want to Play With™, the [import fails](https://i.imgur.com/VCXJn4L.png)

Could this be because the Sources are compiled as a different Module and the `xcconfig` doesn't take this into account when linking the frameworks to the modules where they are required?

Any way I help you with this?

PS: Thanks for this plugin, loving it!

**Comment by neonichu** [comment]
I think there was a previous issue for this and I opened a radar for it. Nothing we can currently do, afaik.

**Comment by piercifani** [comment]
Too bad... 😢 

Well, maybe you can fix this Radar when you'll be on the other side 😉
