### ISSUE TITLE
hi! i run 'pod playgrounds Alamofire', but i got a error 

### ISSUE THREAD

**Issue by hero1981** [asmallteapot/cocoapods-playgrounds#37]
when i run 'pod playgrounds Alamofire'
A error said '[!] Unable to find host target for Pods-AlamofirePlayground. Please add the host targets for the embedded targets to the Podfile.'

And i add 'target 'Pods-AlamofirePlayground' do ... end ' or ' abstract_target 'Pods-AlamofirePlayground' do' to my profile.But none did work. i got the same error words what like above.
How can i fix it? 

my Xcode is 7.3.1, pods is 1.1.0.beta.1

thank you.

**Comment by neonichu** [comment]
This should have been fixed in the latest release 1.2.2 of this plugin, please just update it.
