### ISSUE TITLE
For RxSwift 3.0 with Carthage support

### ISSUE THREAD

**Issue by zh-wowtv** [asmallteapot/cocoapods-playgrounds#38]
I run the command:

> carthage-play ReactiveX/RxSwift

The project and playground files are created. But got the following error message:

> The file /Users/myname/Projects/Swift/ReactiveXPlayground/ReactiveXPlayground/ReactiveX.xcodeproj does not exist.

And got error in playground file too:

> No such module RxSwift

What's wrong with it? Thanks

**Comment by asmallteapot** [comment]
Fixed in #56. A new release is coming soon!
