### ISSUE TITLE
Point to local Pod

### ISSUE THREAD

**Issue by JaviSoto** [asmallteapot/cocoapods-playgrounds#4]
Hey!

This library is absolutely fantastic. I've been trying to use ReactiveCocoa on a playground since playgrounds came out, and today was the first time I finally managed to do it :)

Question: is there a syntax that will create this pointing to a Pod in the local system? Thanks!

**Comment by neonichu** [comment]
Thanks! 

It's not possible at the moment and I have to think a bit on if/how the various Podfile options could be exposed. Maybe `pod playgrounds Foo —path=…` could work, but that would break down with the feature request in #2.

If you just want to point to a newer local version which is also available publicly, you can just run this, close Xcode and change the `pod` declaration in the generated `Podfile` to

``` ruby
pod 'YOLO', :path => '/Users/donaldtrump/Pods/YOLO'
```

and run `pod install` again for the time being.

**Comment by neonichu** [comment]
This is now possible by pointing to a podspec instead of specifying its name:

``` bash
$ pod playgrounds ../../../Sources/Alamofire/Alamofire.podspec
```
