### ISSUE TITLE
Not working in Xcode 8.2

### ISSUE THREAD

**Issue by vjujjavarapu-zz** [asmallteapot/cocoapods-playgrounds#45]
pod playground 'RxSwift, RxCocoa' Does generate a Playground RxSwift but it says no module RxSwift and convert to Swift 3 and once we cover it to Swift 3 it is not working 

Xcode 8.2, Sierra, Swift 3. Please Fix ASAP.

**Comment by segiddins** [comment]
> Please Fix ASAP

This is not likely to get you a quick fix from the community. I believe https://github.com/segiddins/ThisCouldBeUsButYouPlaying/pull/44 may be what you're looking for.

**Comment by vjujjavarapu-zz** [comment]
how can i change the ruby file as mentioned in #44 please let me know

**Comment by vjujjavarapu-zz** [comment]
Hi, 
I have not written or fixed this. I just had to convert to Swift 3 and comment out the XCplayground indefiniteExecution line. and everything works perfect. Thanks.
