### ISSUE TITLE
Better Title

### ISSUE THREAD

**Issue by lfarah** [asmallteapot/cocoapods-playgrounds#8]
Title barely tells about how awesome the library is. Maybe something like PodPlaygrouds?

**Comment by clozach** [comment]
podgrounds? :)

**Comment by clozach** [comment]
Ooh, or maybe CocoaGrounds? Good logo possibilities there!

**Comment by neonichu** [comment]
Thanks for the suggestions, but I'm actually very happy with the project's name :)
